config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :orders, only: [:create, :update, :destroy]
  post '/orders/:id', to: 'orders#create', as: "order_items"
  post '/orders/:id', to: 'orders#update', as: "order_item"
  get '/category/:id', to: 'product_categories#show', as: "category"
  get '/about', to: 'home#about', as: "about"
  get '/contact_us', to: 'home#contact_us', as: "contact_us"
  get '/orders/checkout', to: 'orders#checkout', as: "checkout"
  get '/order/placed', to: 'orders#post_checkout', as: "post_checkout"
  get 'all_products', to: 'products#all_products', as: "all_products"
  get 'featured_products', to: 'products#featured_products', as: "featured_products"
  get 'recent_products', to: 'products#recent_products', as: "recent_products"

  namespace :admin do
    get 'home/index'
    get '/about', to: 'home#about'
  end

  resources :orders, only: [:index] # Add other actions as needed

  resources :payments
  root "home#index"
end

app/models/about.rb
class About < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at", "type", "pamalink"]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at", "type", "pamalink"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  enum status: { new: 0, paid: 1, shipped: 2, cancelled: 3 }, _prefix: :type
  enum payment_method: { cash_on_delivery: 0, online_payment: 1 }

  attr_accessor :city, :province

  TAX_RATE = 0.1 # 10% tax rate

  validates :user, presence: true, if: :user_required?
  validate :user_present

  def total_with_tax
    total = order_items.sum('quantity * price')
    total_with_tax = total * (1 + TAX_RATE)
    total_with_tax
  end

  private

  def user_present
    if user_id.nil?
      errors.add(:user, "is necessary.")
    end
  end

  def user_required?
    !user_id.nil?
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "city", "created_at", "delivery_charges", "id", "payment_method", "status", "total", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["order_items", "user"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :calculate_total_amount
  after_save :update_order

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_id", "price", "product_id", "quantity", "updated_at"]
  end

  private

  def calculate_total_amount
    self.total_amount = quantity.to_f * price.to_f
  end

  def update_order
    order = Order.find_by(id: self.order_id)
    order.total = order.order_items.sum(:total_amount)
    order.save!
  end
end

app/models/product.rb
# app/models/product.rb
class Product < ApplicationRecord
  # Mount uploader for handling product images
  mount_uploader :image, ProductImageUploader

  # Associations
  belongs_to :product_category
  has_many :order_items, dependent: :destroy
  mount_uploader :image, ProductImageUploader

  # Validations
  validate :product_category_present
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than_or_equal_to: 0.01, less_than_or_equal_to: 999999.99 }

  # Scopes
  scope :recent_products, -> { where("products.updated_at >= ?", 3.days.ago) }
  scope :featured_products, -> { where(is_featured: true) }

  # Ransack configuration
  def self.ransackable_attributes(auth_object = nil)
    super + ["created_at", "description", "id", "name", "price", "product_category_id", "quantity", "updated_at", "is_featured" ]
  end

  def self.ransackable_associations(auth_object = nil)
    super + ["order_items", "product_category"]
  end

  private

  # Custom validation to ensure product_category is present
  def product_category_present
    if product_category.nil?
      errors.add(:product_category, "is necessary.")
    end
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "name", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  has_many    :user_roles
  has_many    :users, :through => :user_roles
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :user_roles
  belongs_to :province

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :postal_code, presence: true
  validates :province_id, presence: true
  validates :phone_number, presence: true

  after_create :assign_default_role

  # Add stripe_customer_id attribute
  attribute :stripe_customer_id, :string

  def self.ransackable_attributes(auth_object = nil)
    super + %w[full_name address city postal_code]
  end

  def assign_default_role
    self.add_role(:customer) if self.roles.blank?
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role

  validates :user_id, presence: true
  validates :role_id, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  helper_method :current_order
  before_action :assign_categories

  def current_order
    if session[:order_id].nil?
      Order.new
    else
      begin
        Order.find_by(id: session[:order_id])
      rescue ActiveRecord::RecordNotFound => e
        Order.new
      end
    end
  end

  private

  def assign_categories
    @categories = ProductCategory.where("product_categories.name is not null")
  end
end

app/controllers/carts_controller.rb
class CartsController < BaseController
  add_breadcrumb "home", :root_path

  def show
    add_breadcrumb "products", products_path
    @order_items = current_order.order_items
  rescue ActiveRecord::RecordNotFound
    @order_items = []
  end

  private

  def current_order
    if session[:order_id]
      begin
        @current_order = Order.find(session[:order_id])
      rescue ActiveRecord::RecordNotFound
        session[:order_id] = nil
        @current_order = create_new_order
      end
    else
      @current_order = create_new_order
    end
  end

  def create_new_order
    order = Order.create(user: current_user)
    session[:order_id] = order.id
    order
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if current_user&.has_role? :admin
    #   redirect_to admin_dashboard_path
    # else
      redirect_to products_path
    # end
  end

  def about
    @about = About&.last
  end

  def contact_us
    @contact = Contact.last
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_product.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag(order_item.product.image.thumb.url, class: "img-fluid") %>
  </div>
  <div class="col">
    <div class="card-body">
      <%= form_for order_item, remote: true do |f| %>
        <div class="form-group">
          <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
          <%= f.hidden_field :product_id, value: product.id %>
        </div>
        <div class="btn-group">
          <%= f.submit "Update Quantity", class: "btn btn-primary" %>
          <%= link_to "Delete", order_item, {data: {confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?"}, data: { "turbo-method": :delete }, remote: true, class: "btn btn-danger"} %>
        </div>
        <p>Total Price:
          <%= number_to_currency order_item.price.to_f %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<style>
  /* ... (keep your existing styles) ... */
</style>

<% if @order_items.size == 0 %>
  <div class="shopping-cart">
    <br>
    <br>
    <%= render_breadcrumbs %>
    <% if !@order_item.nil? && @order_item.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @order_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p class="text-center">
      There are no items in your shopping cart. Please <%= link_to "go back", root_path %> and add some items to your cart.
    </p>
  </div>
<% else %>
  <section class="h-100 h-custom" style="background-color: #16a085;">
    <div class="container py-5 h-100">
      <%= render_breadcrumbs %>

      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12">
          <div class="card card-registration card-registration-2" style="border-radius: 15px;">
            <div class="card-body p-0">
              <div class="row g-0">
                <div class="col-lg-8">
                  <div class="p-5">
                    <div class="d-flex justify-content-between align-items-center mb-5">
                      <h1 class="fw-bold mb-0 text-black">Your Products Cart</h1>
                      <h6 class="mb-0 text-muted"><%= @order_items.size %> products</h6>
                    </div>
                    <hr class="my-4">
                    <% @order_items.each do |order_item| %>
                      <%= render 'carts/product', product: order_item.product, order_item: order_item, show_total: true %>
                      <hr class="my-4">
                    <% end %>

                    <div class="pt-5">
                      <h6 class="mb-0"><a href="<%= root_path %>" class="text-body"><i class="fas fa-long-arrow-alt-left me-2"></i>Back to shop</a></h6>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 bg-grey">
                  <div class="p-5">
                    <h3 class="fw-bold mb-5 mt-2 pt-1">Summary</h3>
                    <hr class="my-4">
                    <%= form_with url: checkout_path(@order.id), method: :get do |f| %>
                      <div class="d-flex justify-content-between mb-4">
                        <h5 class="text-uppercase">products <%= @order_items.size %></h5>
                        <h5><%= number_to_currency(@order.total) %></h5>
                      </div>

                      <h5 class="text-uppercase mb-3">Payment Method</h5>
                      <div class="mb-4 pb-2">
                        <%= f.select :payment_method, options_for_select([['Cash on Delivery', 0],['Online Payment', 1]]), {:include_blank => 'Select Payment Method'},  {class: "form-control select"} %>
                      </div>

                      <h5 class="text-uppercase mb-3">Delivery Details</h5>
                      <div class="mb-3">
                        <div class="form-outline">
                          <%= f.text_field :address, id: "form3Examplea2", class: "form-control form-control-lg" %>
                          <label class="form-label" for="form3Examplea2">Street Address</label>
                        </div>
                      </div>
                      <div class="mb-3">
                        <div class="form-outline">
                          <%= f.text_field :city, id: "form3Examplea3", class: "form-control form-control-lg" %>
                          <label class="form-label" for="form3Examplea3">City</label>
                        </div>
                      </div>
                      <div class="mb-5">
                        <div class="form-outline">
                          <%= f.text_field :province, id: "form3Examplea4", class: "form-control form-control-lg" %>
                          <label class="form-label" for="form3Examplea4">Province</label>
                        </div>
                      </div>

                      <hr class="my-4">

                      <div class="d-flex justify-content-between mb-5">
                        <h5 class="text-uppercase">Total price</h5>
                        <h5><%= number_to_currency(@order.total) %></h5>
                      </div>

                      <%= f.submit "Check Out", class: "btn btn-dark btn-block btn-lg" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>