config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :orders, only: [:create, :update, :destroy]
  post '/orders/:id', to: 'orders#create', as: "order_items"
  post '/orders/:id', to: 'orders#update', as: "order_item"
  get '/category/:id', to: 'product_categories#show', as: "category"
  get '/about', to: 'home#about', as: "about"
  get '/contact_us', to: 'home#contact_us', as: "contact_us"
  get '/orders/checkout', to: 'orders#checkout', as: "checkout"
  get '/order/placed', to: 'orders#post_checkout', as: "post_checkout"
  get 'all_products', to: 'products#all_products', as: "all_products"
  get 'featured_products', to: 'products#featured_products', as: "featured_products"
  get 'recent_products', to: 'products#recent_products', as: "recent_products"

  namespace :admin do
    get 'home/index'
    get '/about', to: 'home#about'
  end

  resources :orders, only: [:index] # Add other actions as needed

  resources :payments
  root "home#index"
end

app/models/about.rb
class About < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at", "type", "pamalink"]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at", "type", "pamalink"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  enum status: { new: 0, paid: 1, shipped: 2, cancelled: 3 }, _prefix: :type
  enum payment_method: { cash_on_delivery: 0, online_payment: 1 }

  attr_accessor :city, :province

  TAX_RATE = 0.1 # 10% tax rate

  validates :user, presence: true, if: :user_required?
  validate :user_present

  def total_with_tax
    total = order_items.sum('quantity * price')
    total_with_tax = total * (1 + TAX_RATE)
    total_with_tax
  end

  private

  def user_present
    if user_id.nil?
      errors.add(:user, "is necessary.")
    end
  end

  def user_required?
    !user_id.nil?
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "city", "created_at", "delivery_charges", "id", "payment_method", "status", "total", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["order_items", "user"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :calculate_total_amount
  after_save :update_order

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_id", "price", "product_id", "quantity", "updated_at"]
  end

  private

  def calculate_total_amount
    self.total_amount = quantity.to_f * price.to_f
  end

  def update_order
    order = Order.find_by(id: self.order_id)
    order.total = order.order_items.sum(:total_amount)
    order.save!
  end
end

app/models/product.rb
# app/models/product.rb
class Product < ApplicationRecord
  # Mount uploader for handling product images
  mount_uploader :image, ProductImageUploader

  # Associations
  belongs_to :product_category
  has_many :order_items, dependent: :destroy
  mount_uploader :image, ProductImageUploader

  # Validations
  validate :product_category_present
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than_or_equal_to: 0.01, less_than_or_equal_to: 999999.99 }

  # Scopes
  scope :recent_products, -> { where("products.updated_at >= ?", 3.days.ago) }
  scope :featured_products, -> { where(is_featured: true) }

  # Ransack configuration
  def self.ransackable_attributes(auth_object = nil)
    super + ["created_at", "description", "id", "name", "price", "product_category_id", "quantity", "updated_at", "is_featured" ]
  end

  def self.ransackable_associations(auth_object = nil)
    super + ["order_items", "product_category"]
  end

  private

  # Custom validation to ensure product_category is present
  def product_category_present
    if product_category.nil?
      errors.add(:product_category, "is necessary.")
    end
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "name", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  has_many    :user_roles
  has_many    :users, :through => :user_roles
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :user_roles
  belongs_to :province

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :postal_code, presence: true
  validates :province_id, presence: true
  validates :phone_number, presence: true

  after_create :assign_default_role

  # Add stripe_customer_id attribute
  attribute :stripe_customer_id, :string

  def self.ransackable_attributes(auth_object = nil)
    super + %w[full_name address city postal_code]
  end

  def assign_default_role
    self.add_role(:customer) if self.roles.blank?
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role

  validates :user_id, presence: true
  validates :role_id, presence: true
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  helper_method :current_order
  before_action :assign_categories

  def current_order
    if session[:order_id].nil?
      Order.new
    else
      begin
        Order.find_by(id: session[:order_id])
      rescue ActiveRecord::RecordNotFound => e
        Order.new
      end
    end
  end

  private

  def assign_categories
    @categories = ProductCategory.where("product_categories.name is not null")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if current_user&.has_role? :admin
    #   redirect_to admin_dashboard_path
    # else
      redirect_to products_path
    # end
  end

  def about
    @about = About&.last
  end

  def contact_us
    @contact = Contact.last
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_auth.html.erb
<% if user_signed_in? %>
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <%= link_to current_user.email, "#", class: "nav-link dropdown-toggle", role: "button", "data-bs-toggle": "dropdown" %>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, :class => 'dropdown-item' %>
        <%= link_to "Edit User", edit_user_registration_path, data: { "turbo-method": :get }, :class => 'dropdown-item' %>
        <%= link_to "My Orders", orders_path, class: "dropdown-item" %>
      </div>
    </li>
  </ul>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary mx-1", role: "button" %>
  <%= link_to "Login", new_user_session_path, class: "btn btn-primary", role: "button" %>
<% end %>

app/views/layouts/_cart.html.erb
<div class="cart-text">
  <%= link_to cart_path, class: "btn btn-outline-dark" do %>
    <i class="bi bi-cart4"></i>
    <% if current_order.present? %>
      <%= current_order.order_items.size %>  Products in Cart 
    <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <div class="container-fluid">
    <%= link_to "PrettyHub", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Move the category selection outside of the collapsible section -->
    <ul class="navbar-nav me-auto mb-2 mb-md-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Categories
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% @categories&.each do |cat| %>
            <%= link_to cat.name.capitalize, category_path(cat), class: "dropdown-item" %>
          <% end %>
        </ul>
      </li>
    </ul>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="/featured_products">Feature Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/recent_products">Recent Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/all_products">All Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About PrettyHub</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact_us">Contact us</a>
        </li>
        <li class="nav-item">
          <%= form_tag all_products_path, :method => "get", :class => "form-inline" do %>
            <%=  text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Product Name?" %>
            <%= select_tag(:category_id, options_from_collection_for_select(ProductCategory.all, :id, :name), prompt: 'Select a category') %>
            <%= submit_tag("Search", :name=>nil) %>
          <% end %>
        </li>
      </ul>
      <form class="d-flex">
        <%= render 'layouts/cart' %>
        <%= render 'layouts/auth' %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PrettyHub</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <% if %w[orders products home product_categories carts payments].include?(controller_name) %>
    <%= render "layouts/header" %>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>